// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oknvpipzzgfufvqssauz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbnZwaXB6emdmdWZ2cXNzYXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDI3NTEsImV4cCI6MjA2NzUxODc1MX0.gCkp0NyoWFaRlSQi6tKmb7R5p1BN_2HroZ6IuR7w7xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});